#pragma once

#ifndef KISAK_SP 
#error This file is for SinglePlayer only 
#endif

// LWSS: not sure this .h is supposed to exist.

actor_s *__fastcall Actor_Get(scr_entref_t *entref);
void __fastcall Actor_SetScriptGoalPos(actor_s *self, const float *vGoalPos, pathnode_t *node);
void __fastcall ActorCmd_StartScriptedAnim(scr_entref_t *entref);
void __fastcall Actor_StartArrivalState(actor_s *self, ai_state_t newState);
void __fastcall ActorCmd_StartCoverArrival(scr_entref_t *entref);
void __fastcall ActorCmd_StartTraverseArrival(scr_entref_t *entref);
void __fastcall ActorCmd_CheckCoverExitPosWithPath(scr_entref_t *entref);
void __fastcall ActorCmd_Shoot(scr_entref_t *entref);
void __fastcall ActorCmd_ShootBlank(scr_entref_t *entref);
void __fastcall ActorCmd_Melee(scr_entref_t *entref);
void __fastcall ActorCmd_UpdatePlayerSightAccuracy(scr_entref_t *entref);
void __fastcall ActorCmd_FindCoverNode(scr_entref_t *entref);
void __fastcall ActorCmd_FindBestCoverNode(scr_entref_t *entref);
void __fastcall ActorCmd_GetCoverNode(scr_entref_t *entref);
void __fastcall ActorCmd_UseCoverNode(scr_entref_t *entref);
void __fastcall ActorCmd_ReacquireStep(scr_entref_t *entref);
void __fastcall ActorCmd_FindReacquireNode(scr_entref_t *entref);
void __fastcall ActorCmd_GetReacquireNode(scr_entref_t *entref);
void __fastcall ActorCmd_UseReacquireNode(scr_entref_t *entref);
void __fastcall ActorCmd_FindReacquireDirectPath(scr_entref_t *entref);
void __fastcall ActorCmd_FindReacquireProximatePath(scr_entref_t *entref);
void __fastcall ActorCmd_TrimPathToAttack(scr_entref_t *entref);
void __fastcall ActorCmd_ReacquireMove(scr_entref_t *entref);
void __fastcall ActorCmd_FlagEnemyUnattackable(scr_entref_t *entref);
void __fastcall ActorCmd_SetAimAnims(scr_entref_t *entref);
void __fastcall ActorCmd_AimAtPos(scr_entref_t *entref);
void __fastcall ActorCmd_EnterProne(scr_entref_t *entref);
void __fastcall ActorCmd_ExitProne(scr_entref_t *entref);
void __fastcall ActorCmd_SetProneAnimNodes(scr_entref_t *entref);
void __fastcall ActorCmd_UpdateProne(scr_entref_t *entref);
void __fastcall ActorCmd_ClearPitchOrient(scr_entref_t *entref);
void __fastcall ActorCmd_SetLookAtAnimNodes(scr_entref_t *entref);
void __fastcall ActorCmd_SetLookAt(scr_entref_t *entref);
void __fastcall ActorCmd_SetLookAtYawLimits(scr_entref_t *entref);
void __fastcall ActorCmd_StopLookAt(scr_entref_t *entref);
void __fastcall ActorCmd_CanShoot(scr_entref_t *entref);
void __fastcall ActorCmd_CanSee(scr_entref_t *entref);
void __fastcall ActorCmd_DropWeapon(scr_entref_t *entref);
void __fastcall DEBUGMAYMOVE(float *vec1, float *vec2, const float *color, DEBUGMAYMOVE_LIFT_ENUM liftBehavior);
int __fastcall MayMove_CheckFriendlyFire(actor_s *self, float *start, const float *end);
int __fastcall MayMove_TraceCheck(actor_s *self, float *vStart, float *vEnd, int allowStartSolid, int checkDrop);
void __fastcall ActorCmd_MayMoveToPoint(scr_entref_t *entref);
void __fastcall ActorCmd_MayMoveFromPointToPoint(scr_entref_t *entref);
void __fastcall ActorCmd_Teleport(scr_entref_t *entref);
void __fastcall ActorCmd_WithinApproxPathDist(scr_entref_t *entref);
void __fastcall ActorCmd_IsPathDirect(scr_entref_t *entref);
void __fastcall ActorCmd_AllowedStances(scr_entref_t *entref);
void __fastcall ActorCmd_IsStanceAllowed(scr_entref_t *entref);
void __fastcall ActorCmd_IsSuppressionWaiting(scr_entref_t *entref);
void __fastcall ActorCmd_IsSuppressed(scr_entref_t *entref);
void __fastcall ActorCmd_IsMoveSuppressed(scr_entref_t *entref);
void __fastcall ActorCmd_CheckGrenadeThrow(scr_entref_t *entref);
void __fastcall ActorCmd_CheckGrenadeThrowPos(scr_entref_t *entref);
void __fastcall ActorCmd_ThrowGrenade(scr_entref_t *entref);
bool __fastcall Actor_CheckGrenadeLaunch(actor_s *self, const float *vStartPos, const float *vOffset);
void __fastcall ActorCmd_CheckGrenadeLaunch(scr_entref_t *entref);
void __fastcall ActorCmd_CheckGrenadeLaunchPos(scr_entref_t *entref);
void __fastcall ActorCmd_FireGrenadeLauncher(scr_entref_t *entref);
void __fastcall ActorCmd_PickUpGrenade(scr_entref_t *entref);
void __fastcall ActorCmd_UseTurret(scr_entref_t *entref);
void __fastcall ActorCmd_StopUseTurret(scr_entref_t *entref);
void __fastcall ActorCmd_CanUseTurret(scr_entref_t *entref);
void __fastcall ActorCmd_TraverseMode(scr_entref_t *entref);
void __fastcall ActorCmd_AnimMode(scr_entref_t *entref);
void __fastcall ActorCmd_OrientMode(scr_entref_t *entref);
void __fastcall ActorCmd_GetMotionAngle(scr_entref_t *entref);
void __fastcall ActorCmd_GetAnglesToLikelyEnemyPath(scr_entref_t *entref);
void __fastcall ActorCmd_SetTurretAnim(scr_entref_t *entref);
void __fastcall ActorCmd_GetTurret(scr_entref_t *entref);
void __fastcall ActorCmd_BeginPrediction(scr_entref_t *entref);
void __fastcall ActorCmd_EndPrediction(scr_entref_t *entref);
void __fastcall ActorCmd_LerpPosition(scr_entref_t *entref);
void __fastcall ActorCmd_PredictOriginAndAngles(scr_entref_t *entref);
void __fastcall ActorCmd_PredictAnim(scr_entref_t *entref);
void __fastcall Actor_GetEntType(int entnum);
void __fastcall ActorCmd_GetHitEntType(scr_entref_t *entref);
void __fastcall ActorCmd_GetHitYaw(scr_entref_t *entref);
void __fastcall ActorCmd_GetGroundEntType(scr_entref_t *entref);
void __fastcall ActorCmd_IsDeflected(scr_entref_t *entref);
void __fastcall ActorCmd_trackScriptState(scr_entref_t *entref);
// attributes: thunk
void __fastcall ActorCmd_DumpHistory(scr_entref_t *entref);
void __fastcall ScrCmd_animcustom(scr_entref_t *entref);
void __fastcall ScrCmd_CanAttackEnemyNode(scr_entref_t *entref);
void __fastcall ScrCmd_GetNegotiationStartNode(scr_entref_t *entref);
void __fastcall ScrCmd_GetNegotiationEndNode(scr_entref_t *entref);
void __fastcall ActorCmd_CheckProne(scr_entref_t *entref);
void __fastcall ActorCmd_PushPlayer(scr_entref_t *entref);
void __fastcall Actor_SetScriptGoalVolume(actor_s *self, gentity_s *volume);
void __fastcall ActorCmd_SetGoalNode(scr_entref_t *entref);
void __fastcall Actor_SetScriptGoalEntity(actor_s *self, gentity_s *pGoalEnt);
void __fastcall ActorCmd_SetGoalPos(scr_entref_t *entref);
void __fastcall ActorCmd_SetGoalEntity(scr_entref_t *entref);
void __fastcall ActorCmd_SetGoalVolume(scr_entref_t *entref);
void __fastcall ActorCmd_GetGoalVolume(scr_entref_t *entref);
void __fastcall ActorCmd_ClearGoalVolume(scr_entref_t *entref);
void __fastcall ActorCmd_SetFixedNodeSafeVolume(scr_entref_t *entref);
void __fastcall ActorCmd_GetFixedNodeSafeVolume(scr_entref_t *entref);
void __fastcall ActorCmd_ClearFixedNodeSafeVolume(scr_entref_t *entref);
void __fastcall ActorCmd_IsInGoal(scr_entref_t *entref);
void __fastcall ActorCmd_SetOverrideRunToPos(scr_entref_t *entref);
void __fastcall ActorCmd_NearNode(scr_entref_t *entref);
void __fastcall ActorCmd_ClearEnemy(scr_entref_t *entref);
void __fastcall ActorCmd_SetEntityTarget(scr_entref_t *entref);
void __fastcall ActorCmd_ClearEntityTarget(scr_entref_t *entref);
void __fastcall ActorCmd_SetPotentialThreat(scr_entref_t *entref);
void __fastcall ActorCmd_ClearPotentialThreat(scr_entref_t *entref);
void __fastcall ActorCmd_SetFlashBanged(scr_entref_t *entref);
void __fastcall ActorCmd_SetFlashbangImmunity(scr_entref_t *entref);
void __fastcall ActorCmd_GetFlashBangedStrength(scr_entref_t *entref);
void __fastcall ActorCmd_SetEngagementMinDist(scr_entref_t *entref);
void __fastcall ActorCmd_SetEngagementMaxDist(scr_entref_t *entref);
void __fastcall ActorCmd_IsKnownEnemyInRadius(scr_entref_t *entref);
void __fastcall ActorCmd_IsKnownEnemyInVolume(scr_entref_t *entref);
void __fastcall ActorCmd_SetTalkToSpecies(scr_entref_t *entref);
void(__fastcall *__fastcall Actor_GetMethod(const char **pName))(scr_entref_t);
