#include "com_constantconfigstrings.h"
#include "assertive.h"
#include <string.h>
#include <ctype.h>
#include "q_shared.h"


char tempString[2048];
// struct constantConfigString *constantConfigStrings 827b8848     com_constantconfigstrings.obj
constantConfigString constantConfigStrings[833] = {
    { 20, "bg_aimSpreadMoveSpeedThreshold" },
    { 21, "bg_bobAmplitudeDucked" },
    { 22, "bg_bobAmplitudeProne" },
    { 23, "bg_bobAmplitudeSprinting" },
    { 24, "bg_bobAmplitudeStanding" },
    { 25, "bg_bobMax" },
    { 26, "bg_fallDamageMaxHeight" },
    { 27, "bg_fallDamageMinHeight" },
    { 28, "bg_foliagesnd_fastinterval" },
    { 29, "bg_foliagesnd_maxspeed" },
    { 30, "bg_foliagesnd_minspeed" },
    { 31, "bg_foliagesnd_resetinterval" },
    { 32, "bg_foliagesnd_slowinterval" },
    { 33, "bg_ladder_yawcap" },
    { 34, "bg_maxGrenadeIndicatorSpeed" },
    { 35, "bg_prone_yawcap" },
    { 36, "cg_thirdPersonAngle" },
    { 37, "friction" },
    { 38, "g_ScoresColor_Allies" },
    { 39, "g_ScoresColor_Axis" },
    { 40, "g_ScoresColor_EnemyTeam" },
    { 41, "g_ScoresColor_Free" },
    { 42, "g_ScoresColor_MyTeam" },
    { 43, "g_ScoresColor_Spectator" },
    { 44, "g_TeamColor_Allies" },
    { 45, "g_TeamColor_Axis" },
    { 46, "g_TeamColor_EnemyTeam" },
    { 47, "g_TeamColor_Free" },
    { 48, "g_TeamColor_MyTeam" },
    { 49, "g_TeamColor_Spectator" },
    { 50, "g_TeamIcon_Allies" },
    { 51, "g_TeamIcon_Axis" },
    { 52, "g_TeamIcon_Free" },
    { 53, "g_TeamIcon_Spectator" },
    { 54, "g_TeamName_Allies" },
    { 55, "g_TeamName_Axis" },
    { 56, "inertiaAngle" },
    { 57, "inertiaDebug" },
    { 58, "inertiaMax" },
    { 59, "jump_height" },
    { 60, "jump_ladderPushVel" },
    { 61, "jump_slowdownEnable" },
    { 62, "jump_spreadAdd" },
    { 63, "jump_stepSize" },
    { 64, "mantle_check_angle" },
    { 65, "mantle_check_radius" },
    { 66, "mantle_check_range" },
    { 67, "mantle_debug" },
    { 68, "mantle_enable" },
    { 69, "mantle_view_yawcap" },
    { 70, "player_adsExitDelay" },
    { 71, "player_backSpeedScale" },
    { 72, "player_breath_fire_delay" },
    { 73, "player_breath_gasp_lerp" },
    { 74, "player_breath_gasp_scale" },
    { 75, "player_breath_gasp_time" },
    { 76, "player_breath_hold_lerp" },
    { 77, "player_breath_hold_time" },
    { 78, "player_breath_snd_delay" },
    { 79, "player_breath_snd_lerp" },
    { 80, "player_debugHealth" },
    { 81, "player_dmgtimer_flinchTime" },
    { 82, "player_dmgtimer_maxTime" },
    { 83, "player_dmgtimer_minScale" },
    { 84, "player_dmgtimer_stumbleTime" },
    { 85, "player_dmgtimer_timePerPoint" },
    { 86, "player_footstepsThreshhold" },
    { 87, "player_moveThreshhold" },
    { 88, "player_runbkThreshhold" },
    { 89, "player_runThreshhold" },
    { 90, "player_scopeExitOnDamage" },
    { 91, "player_spectateSpeedScale" },
    { 92, "player_sprintCameraBo" },
    { 93, "player_sprintForwardMinimum" },
    { 94, "player_sprintMinTime" },
    { 95, "player_sprintRechargePause" },
    { 96, "player_sprintSpeedScale" },
    { 97, "player_sprintStrafeSpeedScale" },
    { 98, "player_sprintThreshhold" },
    { 99, "player_sprintTime" },
    { 100, "player_strafeAnimCosAngle" },
    { 101, "player_strafeSpeedScale" },
    { 102, "player_turnAnims" },
    { 103, "player_view_pitch_down" },
    { 104, "player_view_pitch_up" },
    { 105, "scr_allies" },
    { 106, "scr_axis" },
    { 107, "scr_oldschool" },
    { 108, "stopspeed" },
    { 350, "PLATFORM_HOLD_TO_USE" },
    { 351, "PLATFORM_HOLD_TO_DROP" },
    { 390, "PERKS_EAVESDROP" },
    { 391, "PERKS_UAV_JAMMER" },
    { 392, "PERKS_IRON_LUNGS" },
    { 393, "PERKS_DEAD_SILENCE" },
    { 394, "PERKS_EXTREME_CONDITIONING" },
    { 395, "PERKS_BOMB_SQUAD" },
    { 396, "PERKS_SONIC_BOOM" },
    { 397, "PERKS_LAST_STAND" },
    { 398, "PERKS_MARTYRDOM" },
    { 399, "PERKS_STOPPING_POWER" },
    { 400, "PERKS_DEEP_IMPACT" },
    { 401, "PERKS_STEADY_AIM" },
    { 402, "PERKS_DOUBLE_TAP" },
    { 403, "PERKS_SLEIGHT_OF_HAND" },
    { 404, "PERKS_BANDOLIER" },
    { 405, "PERKS_OVERKILL" },
    { 406, "PERKS_JUGGERNAUT" },
    { 407, "PERKS_FRAG_X_3" },
    { 408, "PERKS_SPECIAL_GRENADES_X_3" },
    { 409, "PERKS_C4_X_2" },
    { 410, "PERKS_CLAYMORE_X_2" },
    { 411, "PERKS_RPG7_X_2" },
    { 412, "PERKS_NONE" },
    { 413, "PERKS_GRENADE_LAUNCHER" },
    { 414, "PERKS_GRIP" },
    { 415, "PERKS_ATTACHMENT" },
    { 416, "RANK_PLAYER_WAS_PROMOTED_N" },
    { 417, "RANK_PLAYER_WAS_PROMOTED" },
    { 418, "RANK_PROMOTED" },
    { 419, "MP_PLUS" },
    { 420, "RANK_ROMANI" },
    { 421, "RANK_ROMANII" },
    { 422, "RANK_PFC_FULL" },
    { 423, "RANK_PFC_FULL_N" },
    { 424, "RANK_LCPL_FULL" },
    { 425, "RANK_LCPL_FULL_N" },
    { 426, "RANK_CPL_FULL" },
    { 427, "RANK_CPL_FULL_N" },
    { 428, "RANK_SGT_FULL" },
    { 429, "RANK_SGT_FULL_N" },
    { 430, "RANK_SSGT_FULL" },
    { 431, "RANK_SSGT_FULL_N" },
    { 432, "RANK_GYSGT_FULL" },
    { 433, "RANK_GYSGT_FULL_N" },
    { 434, "RANK_MSGT_FULL" },
    { 435, "RANK_MSGT_FULL_N" },
    { 436, "RANK_MGYSGT_FULL" },
    { 437, "RANK_MGYSGT_FULL_N" },
    { 438, "RANK_2NDLT_FULL" },
    { 439, "RANK_2NDLT_FULL_N" },
    { 440, "RANK_1STLT_FULL" },
    { 441, "RANK_1STLT_FULL_N" },
    { 442, "RANK_CAPT_FULL" },
    { 443, "RANK_CAPT_FULL_N" },
    { 444, "RANK_MAJ_FULL" },
    { 445, "RANK_MAJ_FULL_N" },
    { 446, "RANK_LTCOL_FULL" },
    { 447, "RANK_LTCOL_FULL_N" },
    { 448, "RANK_COL_FULL" },
    { 449, "RANK_COL_FULL_N" },
    { 450, "RANK_BGEN_FULL" },
    { 451, "RANK_BGEN_FULL_N" },
    { 452, "RANK_MAJGEN_FULL" },
    { 453, "RANK_MAJGEN_FULL_N" },
    { 454, "RANK_LTGEN_FULL" },
    { 455, "RANK_LTGEN_FULL_N" },
    { 456, "RANK_GEN_FULL" },
    { 457, "RANK_GEN_FULL_N" },
    { 458, "RANK_COMM_FULL" },
    { 459, "CHALLENGE_M16_MARKSMAN_I" },
    { 460, "CHALLENGE_M16_MARKSMAN_II" },
    { 461, "CHALLENGE_M16_MARKSMAN_III" },
    { 462, "CHALLENGE_M16_EXPERT_I" },
    { 463, "CHALLENGE_M16_EXPERT_II" },
    { 464, "CHALLENGE_M16_EXPERT_III" },
    { 465, "CHALLENGE_AK47_MARKSMAN_I" },
    { 466, "CHALLENGE_AK47_MARKSMAN_II" },
    { 467, "CHALLENGE_AK47_MARKSMAN_III" },
    { 468, "CHALLENGE_AK47_EXPERT_I" },
    { 469, "CHALLENGE_AK47_EXPERT_II" },
    { 470, "CHALLENGE_AK47_EXPERT_III" },
    { 471, "CHALLENGE_G3_MARKSMAN_I" },
    { 472, "CHALLENGE_G3_MARKSMAN_II" },
    { 473, "CHALLENGE_G3_MARKSMAN_III" },
    { 474, "CHALLENGE_G3_EXPERT_I" },
    { 475, "CHALLENGE_G3_EXPERT_II" },
    { 476, "CHALLENGE_G3_EXPERT_III" },
    { 477, "CHALLENGE_M4_MARKSMAN_I" },
    { 478, "CHALLENGE_M4_MARKSMAN_II" },
    { 479, "CHALLENGE_M4_MARKSMAN_III" },
    { 480, "CHALLENGE_M4_EXPERT_I" },
    { 481, "CHALLENGE_M4_EXPERT_II" },
    { 482, "CHALLENGE_M4_EXPERT_III" },
    { 483, "CHALLENGE_M14_MARKSMAN_I" },
    { 484, "CHALLENGE_M14_MARKSMAN_II" },
    { 485, "CHALLENGE_M14_MARKSMAN_III" },
    { 486, "CHALLENGE_M14_EXPERT_I" },
    { 487, "CHALLENGE_M14_EXPERT_II" },
    { 488, "CHALLENGE_M14_EXPERT_III" },
    { 489, "CHALLENGE_G36C_MARKSMAN_I" },
    { 490, "CHALLENGE_G36C_MARKSMAN_II" },
    { 491, "CHALLENGE_G36C_MARKSMAN_III" },
    { 492, "CHALLENGE_G36C_EXPERT_I" },
    { 493, "CHALLENGE_G36C_EXPERT_II" },
    { 494, "CHALLENGE_G36C_EXPERT_III" },
    { 495, "CHALLENGE_MP44_EXPERT_I" },
    { 496, "CHALLENGE_MP44_EXPERT_II" },
    { 497, "CHALLENGE_MP44_EXPERT_III" },
    { 498, "CHALLENGE_MP5_MARKSMAN_I" },
    { 499, "CHALLENGE_MP5_MARKSMAN_II" },
    { 500, "CHALLENGE_MP5_MARKSMAN_III" },
    { 501, "CHALLENGE_MP5_EXPERT_I" },
    { 502, "CHALLENGE_MP5_EXPERT_II" },
    { 503, "CHALLENGE_MP5_EXPERT_III" },
    { 504, "CHALLENGE_SKORPION_MARKSMAN_I" },
    { 505, "CHALLENGE_SKORPION_MARKSMAN_II" },
    { 506, "CHALLENGE_SKORPION_MARKSMAN_III" },
    { 507, "CHALLENGE_SKORPION_EXPERT_I" },
    { 508, "CHALLENGE_SKORPION_EXPERT_II" },
    { 509, "CHALLENGE_SKORPION_EXPERT_III" },
    { 510, "CHALLENGE_MINIUZI_MARKSMAN_I" },
    { 511, "CHALLENGE_MINIUZI_MARKSMAN_II" },
    { 512, "CHALLENGE_MINIUZI_MARKSMAN_III" },
    { 513, "CHALLENGE_MINIUZI_EXPERT_I" },
    { 514, "CHALLENGE_MINIUZI_EXPERT_II" },
    { 515, "CHALLENGE_MINIUZI_EXPERT_III" },
    { 516, "CHALLENGE_AK74U_MARKSMAN_I" },
    { 517, "CHALLENGE_AK74U_MARKSMAN_II" },
    { 518, "CHALLENGE_AK74U_MARKSMAN_III" },
    { 519, "CHALLENGE_AK74U_EXPERT_I" },
    { 520, "CHALLENGE_AK74U_EXPERT_II" },
    { 521, "CHALLENGE_AK74U_EXPERT_III" },
    { 522, "CHALLENGE_P90_MARKSMAN_I" },
    { 523, "CHALLENGE_P90_MARKSMAN_II" },
    { 524, "CHALLENGE_P90_MARKSMAN_III" },
    { 525, "CHALLENGE_P90_EXPERT_I" },
    { 526, "CHALLENGE_P90_EXPERT_II" },
    { 527, "CHALLENGE_P90_EXPERT_III" },
    { 528, "CHALLENGE_M249_SAW_MARKSMAN_I" },
    { 529, "CHALLENGE_M249_SAW_MARKSMAN_II" },
    { 530, "CHALLENGE_M249_SAW_MARKSMAN_III" },
    { 531, "CHALLENGE_M249_SAW_EXPERT_I" },
    { 532, "CHALLENGE_M249_SAW_EXPERT_II" },
    { 533, "CHALLENGE_M249_SAW_EXPERT_III" },
    { 534, "CHALLENGE_RPD_MARKSMAN_I" },
    { 535, "CHALLENGE_RPD_MARKSMAN_II" },
    { 536, "CHALLENGE_RPD_MARKSMAN_III" },
    { 537, "CHALLENGE_RPD_EXPERT_I" },
    { 538, "CHALLENGE_RPD_EXPERT_II" },
    { 539, "CHALLENGE_RPD_EXPERT_III" },
    { 540, "CHALLENGE_M60E4_MARKSMAN_I" },
    { 541, "CHALLENGE_M60E4_MARKSMAN_II" },
    { 542, "CHALLENGE_M60E4_MARKSMAN_III" },
    { 543, "CHALLENGE_M60E4_EXPERT_I" },
    { 544, "CHALLENGE_M60E4_EXPERT_II" },
    { 545, "CHALLENGE_M60E4_EXPERT_III" },
    { 546, "CHALLENGE_W1200_MARKSMAN_I" },
    { 547, "CHALLENGE_W1200_MARKSMAN_II" },
    { 548, "CHALLENGE_W1200_EXPERT_I" },
    { 549, "CHALLENGE_W1200_EXPERT_II" },
    { 550, "CHALLENGE_W1200_EXPERT_III" },
    { 551, "CHALLENGE_BENELLI_M4_MARKSMAN_I" },
    { 552, "CHALLENGE_BENELLI_M4_MARKSMAN_II" },
    { 553, "CHALLENGE_BENELLI_M4_EXPERT_I" },
    { 554, "CHALLENGE_BENELLI_M4_EXPERT_II" },
    { 555, "CHALLENGE_BENELLI_M4_EXPERT_III" },
    { 556, "CHALLENGE_M40A3_MARKSMAN" },
    { 557, "CHALLENGE_M40A3_EXPERT_I" },
    { 558, "CHALLENGE_M40A3_EXPERT_II" },
    { 559, "CHALLENGE_M40A3_EXPERT_III" },
    { 560, "CHALLENGE_M21_MARKSMAN" },
    { 561, "CHALLENGE_M21_EXPERT_I" },
    { 562, "CHALLENGE_M21_EXPERT_II" },
    { 563, "CHALLENGE_M21_EXPERT_III" },
    { 564, "CHALLENGE_DRAGUNOV_MARKSMAN" },
    { 565, "CHALLENGE_DRAGUNOV_EXPERT_I" },
    { 566, "CHALLENGE_DRAGUNOV_EXPERT_II" },
    { 567, "CHALLENGE_DRAGUNOV_EXPERT_III" },
    { 568, "CHALLENGE_R700_MARKSMAN" },
    { 569, "CHALLENGE_R700_EXPERT_I" },
    { 570, "CHALLENGE_R700_EXPERT_II" },
    { 571, "CHALLENGE_R700_EXPERT_III" },
    { 572, "CHALLENGE_BARRETT_50_CAL_MARKSMAN" },
    { 573, "CHALLENGE_BARRETT_50_CAL_EXPERT" },
    { 574, "CHALLENGE_BARRETT_50_CAL_EXPERT1" },
    { 575, "CHALLENGE_BARRETT_50_CAL_EXPERT2" },
    { 576, "CHALLENGE_RADAR_INBOUND" },
    { 577, "CHALLENGE_AIRSTRIKE_INBOUND" },
    { 578, "CHALLENGE_CHOPPER_INBOUND" },
    { 579, "CHALLENGE_FLYSWATTER" },
    { 580, "CHALLENGE_MARATHON" },
    { 581, "CHALLENGE_GOODBYE" },
    { 582, "CHALLENGE_BASE_JUMP" },
    { 583, "CHALLENGE_CROUCH_SHOT_I" },
    { 584, "CHALLENGE_CROUCH_SHOT_II" },
    { 585, "CHALLENGE_CROUCH_SHOT_III" },
    { 586, "CHALLENGE_PRONE_SHOT_I" },
    { 587, "CHALLENGE_PRONE_SHOT_II" },
    { 588, "CHALLENGE_PRONE_SHOT_III" },
    { 589, "CHALLENGE_GRENADE_KILL_I" },
    { 590, "CHALLENGE_GRENADE_KILL_II" },
    { 591, "CHALLENGE_GRENADE_KILL_III" },
    { 592, "CHALLENGE_POINT_GUARD_I" },
    { 593, "CHALLENGE_POINT_GUARD_II" },
    { 594, "CHALLENGE_POINT_GUARD_III" },
    { 595, "CHALLENGE_XRAY_VISION_I" },
    { 596, "CHALLENGE_XRAY_VISION_II" },
    { 597, "CHALLENGE_XRAY_VISION_III" },
    { 598, "CHALLENGE_VANDALISM_I" },
    { 599, "CHALLENGE_VANDALISM_II" },
    { 600, "CHALLENGE_VANDALISM_III" },
    { 601, "CHALLENGE_EXPOSED_I" },
    { 602, "CHALLENGE_EXPOSED_II" },
    { 603, "CHALLENGE_EXPOSED_III" },
    { 604, "CHALLENGE_BACKDRAFT_I" },
    { 605, "CHALLENGE_BACKDRAFT_II" },
    { 606, "CHALLENGE_BACKDRAFT_III" },
    { 607, "CHALLENGE_KNIFE_VETERAN_I" },
    { 608, "CHALLENGE_KNIFE_VETERAN_II" },
    { 609, "CHALLENGE_KNIFE_VETERAN_III" },
    { 610, "CHALLENGE_FREEFORALL_VICTOR_I" },
    { 611, "CHALLENGE_FREEFORALL_VICTOR_II" },
    { 612, "CHALLENGE_FREEFORALL_VICTOR_III" },
    { 613, "CHALLENGE_TEAM_PLAYER_I" },
    { 614, "CHALLENGE_TEAM_PLAYER_II" },
    { 615, "CHALLENGE_TEAM_PLAYER_III" },
    { 616, "CHALLENGE_SD_VICTOR_I" },
    { 617, "CHALLENGE_SD_VICTOR_II" },
    { 618, "CHALLENGE_SD_VICTOR_III" },
    { 619, "CHALLENGE_MVP_TEAM_DEATHMATCH" },
    { 620, "CHALLENGE_HARDCORE_TEAM_PLAYER" },
    { 621, "CHALLENGE_HARDCORE_TEAM_PLAYER1" },
    { 622, "CHALLENGE_HARDCORE_TEAM_PLAYER2" },
    { 623, "CHALLENGE_SABOTAGE_VICTOR_I" },
    { 624, "CHALLENGE_SABOTAGE_VICTOR_II" },
    { 625, "CHALLENGE_SABOTAGE_VICTOR_III" },
    { 626, "CHALLENGE_MVP_TEAM_HARDCORE" },
    { 627, "CHALLENGE_BOMB_DOWN" },
    { 628, "CHALLENGE_BOMB_DEFENDER" },
    { 629, "CHALLENGE_BOMB_PLANTER" },
    { 630, "CHALLENGE_HERO" },
    { 631, "CHALLENGE_LAST_MAN_STANDING" },
    { 632, "CHALLENGE_CLAYMORE_SHOT" },
    { 633, "CHALLENGE_ASSAULT_EXPERT_I" },
    { 634, "CHALLENGE_ASSAULT_EXPERT_II" },
    { 635, "CHALLENGE_ASSAULT_EXPERT_III" },
    { 636, "CHALLENGE_SMG_EXPERT_I" },
    { 637, "CHALLENGE_SMG_EXPERT_II" },
    { 638, "CHALLENGE_SMG_EXPERT_III" },
    { 639, "CHALLENGE_LMG_EXPERT_I" },
    { 640, "CHALLENGE_LMG_EXPERT_II" },
    { 641, "CHALLENGE_LMG_EXPERT_III" },
    { 642, "CHALLENGE_LAST_STAND_VETERAN_I" },
    { 643, "CHALLENGE_LAST_STAND_VETERAN_II" },
    { 644, "CHALLENGE_LAST_STAND_VETERAN_III" },
    { 645, "CHALLENGE_MASTER_CHEF_I" },
    { 646, "CHALLENGE_MASTER_CHEF_II" },
    { 647, "CHALLENGE_MASTER_CHEF_III" },
    { 648, "CHALLENGE_AIRSTRIKE_VETERAN_I" },
    { 649, "CHALLENGE_AIRSTRIKE_VETERAN_II" },
    { 650, "CHALLENGE_AIRSTRIKE_VETERAN_III" },
    { 651, "CHALLENGE_CHOPPER_VETERAN_I" },
    { 652, "CHALLENGE_CHOPPER_VETERAN_II" },
    { 653, "CHALLENGE_CHOPPER_VETERAN_III" },
    { 654, "CHALLENGE_STUN_VETERAN_I" },
    { 655, "CHALLENGE_STUN_VETERAN_II" },
    { 656, "CHALLENGE_STUN_VETERAN_III" },
    { 657, "CHALLENGE_MULTIRPG" },
    { 658, "CHALLENGE_MARTYRDOM_VETERAN_I" },
    { 659, "CHALLENGE_MARTYRDOM_VETERAN_II" },
    { 660, "CHALLENGE_MARTYRDOM_VETERAN_III" },
    { 661, "CHALLENGE_CLAY_MORE" },
    { 662, "CHALLENGE_STEALTH_I" },
    { 663, "CHALLENGE_STEALTH_II" },
    { 664, "CHALLENGE_STEALTH_III" },
    { 665, "CHALLENGE_INVISIBLE_I" },
    { 666, "CHALLENGE_INVISIBLE_II" },
    { 667, "CHALLENGE_INVISIBLE_III" },
    { 668, "CHALLENGE_COUNTERCLAYMORE_I" },
    { 669, "CHALLENGE_COUNTERCLAYMORE_II" },
    { 670, "CHALLENGE_COUNTERCLAYMORE_III" },
    { 671, "CHALLENGE_COUNTERC4_I" },
    { 672, "CHALLENGE_COUNTERC4_II" },
    { 673, "CHALLENGE_COUNTERC4_III" },
    { 674, "CHALLENGE_AIRBORNE" },
    { 675, "CHALLENGE_MULTIFRAG" },
    { 676, "CHALLENGE_CARPET_BOM" },
    { 677, "CHALLENGE_MG_MASTER" },
    { 678, "CHALLENGE_SLASHER" },
    { 679, "CHALLENGE_MULTIC4" },
    { 680, "CHALLENGE_HOT_POTATO_I" },
    { 681, "CHALLENGE_HOT_POTATO_II" },
    { 682, "CHALLENGE_HOT_POTATO_III" },
    { 683, "CHALLENGE_CAR_BOM" },
    { 684, "CHALLENGE_BACKSTABBER" },
    { 685, "CHALLENGE_SLOW_BUT_SURE" },
    { 686, "CHALLENGE_FLASHBANG_VETERAN_I" },
    { 687, "CHALLENGE_FLASHBANG_VETERAN_II" },
    { 688, "CHALLENGE_FLASHBANG_VETERAN_III" },
    { 689, "CHALLENGE_MISERY_LOVES_COMPANY" },
    { 690, "CHALLENGE_MISERY_LOVES_COMPANY1" },
    { 691, "CHALLENGE_MISERY_LOVES_COMPANY2" },
    { 692, "CHALLENGE_OUCH_I" },
    { 693, "CHALLENGE_OUCH_II" },
    { 694, "CHALLENGE_OUCH_III" },
    { 695, "CHALLENGE_RIVAL" },
    { 696, "CHALLENGE_CRUELTY" },
    { 697, "CHALLENGE_THINK_FAST" },
    { 698, "CHALLENGE_THINK_FAST_STUN" },
    { 699, "CHALLENGE_THINK_FAST_FLASH" },
    { 700, "CHALLENGE_RETURN_TO_SENDER" },
    { 701, "CHALLENGE_BLINDFIRE" },
    { 702, "CHALLENGE_THE_BRINK" },
    { 703, "CHALLENGE_COLLATERAL_DAMAGE" },
    { 704, "CHALLENGE_THE_EDGE_I" },
    { 705, "CHALLENGE_THE_EDGE_II" },
    { 706, "CHALLENGE_THE_EDGE_III" },
    { 707, "CHALLENGE_FLAWLESS" },
    { 708, "CHALLENGE_TANGO_DOWN" },
    { 709, "CHALLENGE_HARD_LANDING" },
    { 710, "CHALLENGE_EXTREME_CRUELTY" },
    { 711, "CHALLENGE_FAST_SWAP" },
    { 712, "CHALLENGE_STAR_PLAYER" },
    { 713, "CHALLENGE_HOW_THE_" },
    { 714, "CHALLENGE_DOMINOS" },
    { 715, "CHALLENGE_NO_SECRETS" },
    { 716, "CHALLENGE_AFTERBURNER" },
    { 717, "CHALLENGE_AIR_SUPERIORITY" },
    { 718, "CHALLENGE_FEARLESS" },
    { 719, "CHALLENGE_COUNTERMVP" },
    { 720, "CHALLENGE_INVINCIBLE" },
    { 721, "CHALLENGE_SURVIVALIST" },
    { 722, "MP_HOST_ENDGAME_RESPONSE" },
    { 723, "MP_AUTOBALANCE_NOW" },
    { 724, "PLATFORM_PRESS_TO_SKIP" },
    { 725, "PLATFORM_PRESS_TO_RESPAWN" },
    { 726, "MP_EARNED_RADAR" },
    { 727, "MP_EARNED_AIRSTRIKE" },
    { 728, "MP_EARNED_HELICOPTER" },
    { 729, "MP_RADAR_NOT_AVAILABLE" },
    { 730, "MP_AIRSTRIKE_NOT_AVAILABLE" },
    { 731, "MP_HELICOPTER_NOT_AVAILABLE" },
    { 732, "MP_KILLSTREAK_N" },
    { 736, "MP_MATCH_BONUS_IS" },
    { 737, "MP_DEFEAT" },
    { 738, "MP_VICTORY" },
    { 739, "MP_ROUND_LOSS" },
    { 740, "MP_ROUND_WIN" },
    { 741, "MP_DRAW" },
    { 852, "weapon_saw_mg_setup" },
    { 853, "weapon_m4_mp" },
    { 854, "weapon_m4_mp_brock" },
    { 855, "weapon_m4_mp_bshdwl" },
    { 856, "weapon_m4_mp_bwmrpt" },
    { 857, "weapon_m4_mp_cmdtgr" },
    { 858, "weapon_m4_mp_stagger" },
    { 859, "weapon_m82" },
    { 860, "weapon_m82_mp_brock" },
    { 861, "weapon_m82_mp_bshdwl" },
    { 862, "weapon_m82_mp_bwmrpt" },
    { 863, "weapon_m82_mp_cmdtgr" },
    { 864, "weapon_m82_mp_stagger" },
    { 865, "weapon_g36_mp" },
    { 866, "weapon_g36_mp_brock" },
    { 867, "weapon_g36_mp_bshdwl" },
    { 868, "weapon_g36_mp_bwmrpt" },
    { 869, "weapon_g36_mp_cmdtgr" },
    { 870, "weapon_g36_mp_stagger" },
    { 871, "weapon_winchest1200" },
    { 872, "weapon_winchest1200_mp_brock" },
    { 873, "weapon_winchest1200_mp_bshdwl" },
    { 874, "weapon_winchest1200_mp_bwmrpt" },
    { 875, "weapon_winchest1200_mp_cmdtgr" },
    { 876, "weapon_winchest1200_mp_stagger" },
    { 877, "perc_stoppingpower" },
    { 878, "weapon_m67_grenade" },
    { 879, "projectile_m67fraggrenade" },
    { 880, "weapon_mp5sd" },
    { 881, "weapon_mp5sd_mp_brock" },
    { 882, "weapon_mp5sd_mp_bshdwl" },
    { 883, "weapon_mp5sd_mp_bwmrpt" },
    { 884, "weapon_mp5sd_mp_cmdtgr" },
    { 885, "weapon_mp5sd_mp_stagger" },
    { 886, "weapon_desert_eagle_silver" },
    { 887, "weapon_rpg7" },
    { 888, "projectile_rpg7" },
    { 889, "weapon_mini_uzi" },
    { 890, "weapon_mini_uzi_mp_brock" },
    { 891, "weapon_mini_uzi_mp_bshdwl" },
    { 892, "weapon_mini_uzi_mp_bwmrpt" },
    { 893, "weapon_mini_uzi_mp_cmdtgr" },
    { 894, "weapon_mini_uzi_mp_stagger" },
    { 895, "weapon_mini_uzi_gold" },
    { 896, "perc_slieghtofhand" },
    { 897, "perc_doubletap" },
    { 898, "weapon_m14_scout_mp" },
    { 899, "weapon_m14_scout_mp_brock" },
    { 900, "weapon_m14_scout_mp_bshdwl" },
    { 901, "weapon_m14_scout_mp_bwmrpt" },
    { 902, "weapon_m14_scout_mp_cmdtgr" },
    { 903, "weapon_m14_scout_mp_stagger" },
    { 904, "weapon_us_smoke_grenade" },
    { 905, "projectile_us_smoke_grenade" },
    { 906, "weapon_m84_flashbang_grenade" },
    { 907, "projectile_m84_flashbang_grenade" },
    { 908, "vehicle_mig29_desert" },
    { 909, "projectile_cbu97_clusterbom" },
    { 910, "tag_origin" },
    { 933, "weapon_beretta" },
    { 934, "weapon_colt1911_black" },
    { 935, "weapon_usp" },
    { 936, "weapon_desert_eagle_gold" },
    { 937, "weapon_mp5" },
    { 938, "weapon_mp5_mp_brock" },
    { 939, "weapon_mp5_mp_bshdwl" },
    { 940, "weapon_mp5_mp_bwmrpt" },
    { 941, "weapon_mp5_mp_cmdtgr" },
    { 942, "weapon_mp5_mp_stagger" },
    { 943, "weapon_skorpion" },
    { 944, "weapon_skorpion_mp_brock" },
    { 945, "weapon_skorpion_mp_bshdwl" },
    { 946, "weapon_skorpion_mp_bwmrpt" },
    { 947, "weapon_skorpion_mp_cmdtgr" },
    { 948, "weapon_skorpion_mp_stagger" },
    { 949, "weapon_ak74u" },
    { 950, "weapon_ak74u_mp_brock" },
    { 951, "weapon_ak74u_mp_bshdwl" },
    { 952, "weapon_ak74u_mp_bwmrpt" },
    { 953, "weapon_ak74u_mp_cmdtgr" },
    { 954, "weapon_ak74u_mp_stagger" },
    { 955, "weapon_p90" },
    { 956, "weapon_p90_mp_brock" },
    { 957, "weapon_p90_mp_bshdwl" },
    { 958, "weapon_p90_mp_bwmrpt" },
    { 959, "weapon_p90_mp_cmdtgr" },
    { 960, "weapon_p90_mp_stagger" },
    { 961, "weapon_ak47" },
    { 962, "weapon_ak47_mp_brock" },
    { 963, "weapon_ak47_mp_bshdwl" },
    { 964, "weapon_ak47_mp_bwmrpt" },
    { 965, "weapon_ak47_mp_cmdtgr" },
    { 966, "weapon_ak47_mp_stagger" },
    { 967, "weapon_ak47_gold" },
    { 968, "weapon_mp44" },
    { 969, "weapon_mp44_mp_brock" },
    { 970, "weapon_mp44_mp_bshdwl" },
    { 971, "weapon_mp44_mp_bwmrpt" },
    { 972, "weapon_mp44_mp_cmdtgr" },
    { 973, "weapon_mp44_mp_stagger" },
    { 974, "weapon_g3" },
    { 975, "weapon_g3_mp_brock" },
    { 976, "weapon_g3_mp_bshdwl" },
    { 977, "weapon_g3_mp_bwmrpt" },
    { 978, "weapon_g3_mp_cmdtgr" },
    { 979, "weapon_g3_mp_stagger" },
    { 980, "weapon_m16_mp" },
    { 981, "weapon_m16_mp_brock" },
    { 982, "weapon_m16_mp_bshdwl" },
    { 983, "weapon_m16_mp_bwmrpt" },
    { 984, "weapon_m16_mp_cmdtgr" },
    { 985, "weapon_m16_mp_stagger" },
    { 986, "weapon_m16gr_sp" },
    { 987, "weapon_m16m203_mp_brock" },
    { 988, "weapon_m16m203_mp_bshdwl" },
    { 989, "weapon_m16m203_mp_bwmrpt" },
    { 990, "weapon_m16m203_mp_cmdtgr" },
    { 991, "weapon_m16m203_mp_stagger" },
    { 992, "projectile_m203grenade" },
    { 993, "weapon_dragunov" },
    { 994, "weapon_dragunov_mp_brock" },
    { 995, "weapon_dragunov_mp_bshdwl" },
    { 996, "weapon_dragunov_mp_bwmrpt" },
    { 997, "weapon_dragunov_mp_cmdtgr" },
    { 998, "weapon_dragunov_mp_stagger" },
    { 999, "weapon_dragunov_gold" },
    { 1000, "weapon_m40a3" },
    { 1001, "weapon_m40a3_mp_brock" },
    { 1002, "weapon_m40a3_mp_bshdwl" },
    { 1003, "weapon_m40a3_mp_bwmrpt" },
    { 1004, "weapon_m40a3_mp_cmdtgr" },
    { 1005, "weapon_m40a3_mp_stagger" },
    { 1006, "weapon_remington700" },
    { 1007, "weapon_remington700_mp_brock" },
    { 1008, "weapon_remington700_mp_bshdwl" },
    { 1009, "weapon_remington700_mp_bwmrpt" },
    { 1010, "weapon_remington700_mp_cmdtgr" },
    { 1011, "weapon_remington700_mp_stagger" },
    { 1012, "weapon_m14_mp" },
    { 1013, "weapon_m14_mp_brock" },
    { 1014, "weapon_m14_mp_bshdwl" },
    { 1015, "weapon_m14_mp_bwmrpt" },
    { 1016, "weapon_m14_mp_cmdtgr" },
    { 1017, "weapon_m14_mp_stagger" },
    { 1018, "weapon_benelli_super_90" },
    { 1019, "weapon_benelli_super_90_mp_brock" },
    { 1020, "weapon_benelli_super_90_mp_bshdwl" },
    { 1021, "weapon_benelli_super_90_mp_bwmrpt" },
    { 1022, "weapon_benelli_super_90_mp_cmdtgr" },
    { 1023, "weapon_benelli_super_90_mp_stagger" },
    { 1024, "weapon_benelli_super_90_gold" },
    { 1025, "weapon_rpd" },
    { 1026, "weapon_rpd_mp_brock" },
    { 1027, "weapon_rpd_mp_bshdwl" },
    { 1028, "weapon_rpd_mp_bwmrpt" },
    { 1029, "weapon_rpd_mp_cmdtgr" },
    { 1030, "weapon_rpd_mp_stagger" },
    { 1031, "weapon_saw" },
    { 1032, "weapon_saw_mp_brock" },
    { 1033, "weapon_saw_mp_bshdwl" },
    { 1034, "weapon_saw_mp_bwmrpt" },
    { 1035, "weapon_saw_mp_cmdtgr" },
    { 1036, "weapon_saw_mp_stagger" },
    { 1037, "weapon_m60" },
    { 1038, "weapon_m60_mp_brock" },
    { 1039, "weapon_m60_mp_bshdwl" },
    { 1040, "weapon_m60_mp_bwmrpt" },
    { 1041, "weapon_m60_mp_cmdtgr" },
    { 1042, "weapon_m60_mp_stagger" },
    { 1043, "weapon_m60_gold" },
    { 1044, "weapon_c4_mp" },
    { 1045, "weapon_c4" },
    { 1046, "weapon_claymore_no_legs" },
    { 1047, "weapon_claymore" },
    { 1048, "weapon_concussion_grenade" },
    { 1049, "projectile_concussion_grenade" },
    { 1050, "weapon_beretta_silencer" },
    { 1051, "weapon_colt1911_silencer" },
    { 1052, "weapon_usp_silencer" },
    { 1053, "weapon_skorpion_sd" },
    { 1054, "weapon_skorpionsd_mp_brock" },
    { 1055, "weapon_skorpionsd_mp_bshdwl" },
    { 1056, "weapon_skorpionsd_mp_bwmrpt" },
    { 1057, "weapon_skorpionsd_mp_cmdtgr" },
    { 1058, "weapon_skorpionsd_mp_stagger" },
    { 1059, "weapon_mini_uzi_silencer" },
    { 1060, "weapon_mini_uzi_sd_mp_brock" },
    { 1061, "weapon_mini_uzi_sd_mp_bshdwl" },
    { 1062, "weapon_mini_uzi_sd_mp_bwmrpt" },
    { 1063, "weapon_mini_uzi_sd_mp_cmdtgr" },
    { 1064, "weapon_mini_uzi_sd_mp_stagger" },
    { 1065, "weapon_mini_uzi_silencer_gold" },
    { 1066, "weapon_ak74u_supressed" },
    { 1067, "weapon_ak74usd_mp_brock" },
    { 1068, "weapon_ak74usd_mp_bshdwl" },
    { 1069, "weapon_ak74usd_mp_bwmrpt" },
    { 1070, "weapon_ak74usd_mp_cmdtgr" },
    { 1071, "weapon_ak74usd_mp_stagger" },
    { 1072, "weapon_p90_sd" },
    { 1073, "weapon_p90_silencer_mp_brock" },
    { 1074, "weapon_p90_silencer_mp_bshdwl" },
    { 1075, "weapon_p90_silencer_mp_bwmrpt" },
    { 1076, "weapon_p90_silencer_mp_cmdtgr" },
    { 1077, "weapon_p90_silencer_mp_stagger" },
    { 1078, "weapon_ak47_silencer" },
    { 1079, "weapon_ak47sd_mp_brock" },
    { 1080, "weapon_ak47sd_mp_bwmrpt" },
    { 1081, "weapon_ak47sd_mp_cmdtgr" },
    { 1082, "weapon_ak47sd_mp_stagger" },
    { 1083, "weapon_ak47_silencer_gold" },
    { 1084, "weapon_ak47_grenadier" },
    { 1085, "weapon_ak47_grenadier_mp_brock" },
    { 1086, "weapon_ak47_grenadier_mp_bshdwl" },
    { 1087, "weapon_ak47_grenadier_mp_bwmrpt" },
    { 1088, "weapon_ak47_grenadier_mp_cmdtgr" },
    { 1089, "weapon_ak47_grenadier_mp_stagger" },
    { 1090, "weapon_ak47_grenadier_gold" },
    { 1091, "weapon_m14sd_scout" },
    { 1092, "weapon_m14sd_scout_brock" },
    { 1093, "weapon_m14sd_scout_bshdwl" },
    { 1094, "weapon_m14sd_scout_bwmrpt" },
    { 1095, "weapon_m14sd_scout_cmdtgr" },
    { 1096, "weapon_m14sd_scout_stagger" },
    { 1097, "weapon_m14_gl_scout_mp" },
    { 1098, "weapon_m14_gl_scout_mp_brock" },
    { 1099, "weapon_m14_gl_scout_mp_bshdwl" },
    { 1100, "weapon_m14_gl_scout_mp_bwmrpt" },
    { 1101, "weapon_m14_gl_scout_mp_cmdtgr" },
    { 1102, "weapon_m14_gl_scout_mp_stagger" },
    { 1103, "weapon_g3_silencer" },
    { 1104, "weapon_g3sd_mp_brock" },
    { 1105, "weapon_g3sd_mp_bshdwl" },
    { 1106, "weapon_g3sd_mp_bwmrpt" },
    { 1107, "weapon_g3sd_mp_cmdtgr" },
    { 1108, "weapon_g3sd_mp_stagger" },
    { 1109, "weapon_g3m203" },
    { 1110, "weapon_g3m203_brock" },
    { 1111, "weapon_g3m203_bshdwl" },
    { 1112, "weapon_g3m203_bwmrpt" },
    { 1113, "weapon_g3m203_cmdtgr" },
    { 1114, "weapon_g3m203_stagger" },
    { 1115, "weapon_g36csd_mp" },
    { 1116, "weapon_g36csd_mp_brock" },
    { 1117, "weapon_g36csd_mp_bshdwl" },
    { 1118, "weapon_g36csd_mp_bwmrpt" },
    { 1119, "weapon_g36csd_mp_cmdtgr" },
    { 1120, "weapon_g36csd_mp_stagger" },
    { 1121, "weapon_g36m203" },
    { 1122, "weapon_g36m203_brock" },
    { 1123, "weapon_g36m203_bshdwl" },
    { 1124, "weapon_g36m203_bwmrpt" },
    { 1125, "weapon_g36m203_cmdtgr" },
    { 1126, "weapon_g36m203_stagger" },
    { 1127, "weapon_m16_silencer_mp" },
    { 1128, "weapon_m16sd_mp_brock" },
    { 1129, "weapon_m16sd_mp_bshdwl" },
    { 1130, "weapon_m16sd_mp_bwmrpt" },
    { 1131, "weapon_m16sd_mp_cmdtgr" },
    { 1132, "weapon_m16sd_mp_stagger" },
    { 1133, "weapon_m4_silencer_mp" },
    { 1134, "weapon_m4sd_mp_brock" },
    { 1135, "weapon_m4sd_mp_bshdwl" },
    { 1136, "weapon_m4sd_mp_bwmrpt" },
    { 1137, "weapon_m4sd_mp_cmdtgr" },
    { 1138, "weapon_m4sd_mp_stagger" },
    { 1139, "weapon_m4m203_mp" },
    { 1140, "weapon_m4m203_mp_brock" },
    { 1141, "weapon_m4m203_mp_bshdwl" },
    { 1142, "weapon_m4m203_mp_bwmrpt" },
    { 1143, "weapon_m4m203_mp_cmdtgr" },
    { 1144, "weapon_m4m203_mp_stagger" },
    { 1145, "weapon_benelli_super_90_foregrip_mp_brock" },
    { 1146, "weapon_benelli_super_90_foregrip_mp_bshdwl" },
    { 1147, "weapon_benelli_super_90_foregrip_mp_bwmrpt" },
    { 1148, "weapon_benelli_super_90_foregrip_mp_cmdtgr" },
    { 1149, "weapon_benelli_super_90_foregrip_mp_stagger" },
    { 1150, "weapon_benelli_super_90_gold_foregrip" },
    { 1968, "default" },
    { 1969, "concussion_grenade_mp" },
    { 1970, "flashbang" },
    { 1971, "frag_grenade_mp" },
    { 1972, "damage_mp" },
    { 1983, "ingame_controls" },
    { 1984, "ingame_options" },
    { 1985, "popup_leavegame" },
    { 1986, "scoreboard" },
    { 1993, "class" },
    { 1994, "changeclass" },
    { 1996, "changeclass_offline" },
    { 2020, "white" },
    { 2021, "black" },
    { 2022, "specialty_parabolic" },
    { 2023, "specialty_gpsjammer" },
    { 2024, "specialty_holdbreath" },
    { 2025, "specialty_quieter" },
    { 2026, "specialty_longersprint" },
    { 2027, "specialty_detectexplosive" },
    { 2028, "specialty_explosivedamage" },
    { 2029, "specialty_pistoldeath" },
    { 2030, "specialty_grenadepulldeath" },
    { 2031, "specialty_bulletdamage" },
    { 2032, "specialty_bulletpenetration" },
    { 2033, "specialty_bulletaccuracy" },
    { 2034, "specialty_rof" },
    { 2035, "specialty_fastreload" },
    { 2036, "specialty_extraammo" },
    { 2037, "specialty_twoprimaries" },
    { 2038, "specialty_armorvest" },
    { 2039, "specialty_fraggrenade" },
    { 2040, "specialty_specialgrenade" },
    { 2041, "specialty_weapon_c4" },
    { 2042, "specialty_weapon_claymore" },
    { 2043, "specialty_weapon_rpg" },
    { 2044, "specialty_null" },
    { 2045, "waypoint_bombsquad" },
    { 2046, "rank_pfc1" },
    { 2047, "rank_pfc2" },
    { 2048, "rank_pfc3" },
    { 2049, "rank_lcpl1" },
    { 2050, "rank_lcpl2" },
    { 2051, "rank_lcpl3" },
    { 2052, "rank_cpl1" },
    { 2053, "rank_cpl2" },
    { 2054, "rank_cpl3" },
    { 2055, "rank_sgt1" },
    { 2056, "rank_sgt2" },
    { 2057, "rank_sgt3" },
    { 2058, "rank_ssgt1" },
    { 2059, "rank_ssgt2" },
    { 2060, "rank_ssgt3" },
    { 2061, "rank_gysgt1" },
    { 2062, "rank_gysgt2" },
    { 2063, "rank_gysgt3" },
    { 2064, "rank_msgt1" },
    { 2065, "rank_msgt2" },
    { 2066, "rank_msgt3" },
    { 2067, "rank_mgysgt1" },
    { 2068, "rank_mgysgt2" },
    { 2069, "rank_mgysgt3" },
    { 2070, "rank_2ndlt1" },
    { 2071, "rank_2ndlt2" },
    { 2072, "rank_2ndlt3" },
    { 2073, "rank_1stlt1" },
    { 2074, "rank_1stlt2" },
    { 2075, "rank_1stlt3" },
    { 2076, "rank_capt1" },
    { 2077, "rank_capt2" },
    { 2078, "rank_capt3" },
    { 2079, "rank_maj1" },
    { 2080, "rank_maj2" },
    { 2081, "rank_maj3" },
    { 2082, "rank_ltcol1" },
    { 2083, "rank_ltcol2" },
    { 2084, "rank_ltcol3" },
    { 2085, "rank_col1" },
    { 2086, "rank_col2" },
    { 2087, "rank_col3" },
    { 2088, "rank_bgen1" },
    { 2089, "rank_bgen2" },
    { 2090, "rank_bgen3" },
    { 2091, "rank_majgen1" },
    { 2092, "rank_majgen2" },
    { 2093, "rank_majgen3" },
    { 2094, "rank_ltgen1" },
    { 2095, "rank_ltgen2" },
    { 2096, "rank_ltgen3" },
    { 2097, "rank_gen1" },
    { 2098, "rank_gen2" },
    { 2099, "rank_gen3" },
    { 2100, "rank_comm1" },
    { 2101, "rank_prestige1" },
    { 2102, "rank_prestige2" },
    { 2103, "rank_prestige3" },
    { 2104, "rank_prestige4" },
    { 2105, "rank_prestige5" },
    { 2106, "rank_prestige6" },
    { 2107, "rank_prestige7" },
    { 2108, "rank_prestige8" },
    { 2109, "rank_prestige9" },
    { 2110, "rank_prestige10" },
    { 2111, "progress_bar_bg" },
    { 2112, "progress_bar_fg" },
    { 2113, "progress_bar_fill" },
    { 2114, "score_bar_bg" },
    { 2121, "objpoint_default" },
    { 2122, "headicon_dead" },
    { 2123, "damage_feedback" },
    { 2124, "damage_feedback_j" },
    { 2125, "overlay_low_health" },
    { 2271, "defaultweapon_mp saw_bipod_crouch_mp m4_acog_mp barrett_mp g36c_reflex_mp winchester1200_grip_mp frag_grenade_mp mp5_silencer_mp deserteagle_mp rpg_mp uzi_mp m14_mp smoke_grenade_mp flash_grenade_mp beretta_mp colt45_mp usp_mp deserteaglegold_mp mp5_mp skorpion_mp ak74u_mp p90_mp ak47_mp mp44_mp g3_mp g36c_mp m16_mp m4_mp gl_mp m16_gl_mp gl_m16_mp dragunov_mp m40a3_mp remington700_mp m21_mp m1014_mp winchester1200_mp rpd_mp saw_mp m60e4_mp c4_mp claymore_mp concussion_grenade_mp beretta_silencer_mp colt45_silencer_mp usp_silencer_mp mp5_reflex_mp mp5_acog_mp skorpion_reflex_mp skorpion_silencer_mp skorpion_acog_mp uzi_reflex_mp uzi_silencer_mp uzi_acog_mp ak74u_reflex_mp ak74u_silencer_mp ak74u_acog_mp p90_reflex_mp p90_silencer_mp p90_acog_mp ak47_reflex_mp ak47_silencer_mp ak47_acog_mp ak47_gl_mp gl_ak47_mp m14_reflex_mp m14_silencer_mp m14_acog_mp m14_gl_mp gl_m14_mp g3_reflex_mp g3_silencer_mp g3_acog_mp g3_gl_mp gl_g3_mp g36c_silencer_mp g36c_acog_mp g36c_gl_mp gl_g36c_mp m16_reflex_mp m16_silencer_mp m16_acog_mp m4_reflex_mp m4_silencer_mp m4_gl_mp gl_m4_mp dragunov_acog_mp m40a3_acog_mp barrett_acog_mp remington700_acog_mp m21_acog_mp m1014_grip_mp m1014_reflex_mp winchester1200_reflex_mp rpd_acog_mp rpd_grip_mp rpd_reflex_mp saw_acog_mp saw_grip_mp saw_reflex_mp m60e4_acog_mp m60e4_grip_mp m60e4_reflex_mp frag_grenade_short_mp destructible_car briefcase_bomb_mp briefcase_bomb_defuse_mp radar_mp airstrike_mp helicopter_mp artillery_mp cobra_ffar_mp hind_ffar_mp cobra_20mm_mp" },
    { 2272, "hud_status_dead" },
    { 2273, "hud_status_connecting" },
    { 0, "" },
}; // idb
// unsigned int *reservedConfigStrings 850cc100     com_constantconfigstrings.obj
unsigned int reservedConfigStrings[77];
// int constantConfigStringCount 850cc228     com_constantconfigstrings.obj
int constantConfigStringCount;

unsigned int __cdecl GetHashCode(const char *str, unsigned int len)
{
    unsigned int hash; // [esp+4h] [ebp-8h]

    if (len >= 0x100)
        return (len >> 2) % 0x4E1F + 1;
    hash = 0;
    while (len)
    {
        hash = *str++ + 31 * hash;
        --len;
    }
    return hash % 0x4E1F + 1;
}

unsigned int __cdecl GetHashCode_0(const char *str, unsigned int len)
{
    unsigned int hash; // [esp+4h] [ebp-8h]

    if (len >= 0x100)
        return (len >> 2) % 0x7FFFFFFE + 1;
    hash = 0;
    while (len)
    {
        hash = *str++ + 31 * hash;
        --len;
    }
    return hash % 0x7FFFFFFE + 1;
}

unsigned int __cdecl lowercaseHash(const char *str)
{
    char *d; // [esp+10h] [ebp-8h]
    const char *s; // [esp+14h] [ebp-4h]

    if (strlen(str) >= 0x800)
        MyAssertHandler(".\\universal\\com_constantconfigstrings.cpp", 889, 0, "%s", "strlen( str ) < sizeof( tempString )");
    s = str;
    d = tempString;
    while (*s)
        *d++ = tolower(*s++);
    return GetHashCode(tempString, d - tempString);
}

void __cdecl CCS_InitConstantConfigStrings()
{
    int index; // [esp+14h] [ebp-4h]

    for (index = 0; constantConfigStrings[index].configStringNum; ++index)
    {
        if (index && constantConfigStrings[index - 1].configStringNum >= constantConfigStrings[index].configStringNum)
            MyAssertHandler(
                ".\\universal\\com_constantconfigstrings.cpp",
                910,
                0,
                "%s",
                "index == 0 || constantConfigStrings[index-1].configStringNum < constantConfigStrings[index].configStringNum");
        if (constantConfigStrings[index].configStringNum < 821)
            constantConfigStrings[index].configStringHash = GetHashCode_0(
                constantConfigStrings[index].configString,
                strlen(constantConfigStrings[index].configString));
        else
            constantConfigStrings[index].configStringHash = lowercaseHash(constantConfigStrings[index].configString);
        reservedConfigStrings[constantConfigStrings[index].configStringNum / 32] |= 1 << (constantConfigStrings[index].configStringNum
            % 32);
    }
    constantConfigStringCount = index;
}

int __cdecl CCS_GetConstConfigStringIndex(const char *configString)
{
    int hash; // [esp+24h] [ebp-Ch]
    int index; // [esp+28h] [ebp-8h]
    unsigned int lcaseHash; // [esp+2Ch] [ebp-4h]

    index = 0;
    hash = GetHashCode_0(configString, strlen(configString));
    lcaseHash = lowercaseHash(configString);
    while (constantConfigStrings[index].configStringNum)
    {
        if (constantConfigStrings[index].configStringNum < 821)
        {
            if (constantConfigStrings[index].configStringHash == hash
                && !strcmp(configString, constantConfigStrings[index].configString))
            {
                return index;
            }
        }
        else if (constantConfigStrings[index].configStringHash == lcaseHash
            && !I_stricmp(configString, constantConfigStrings[index].configString))
        {
            return index;
        }
        ++index;
    }
    return -1;
}

int __cdecl CCS_GetConfigStringNumForConstIndex(unsigned int index)
{
    if (index >= constantConfigStringCount)
        MyAssertHandler(
            ".\\universal\\com_constantconfigstrings.cpp",
            954,
            0,
            "index doesn't index constantConfigStringCount\n\t%i not in [0, %i)",
            index,
            constantConfigStringCount);
    return constantConfigStrings[index].configStringNum;
}

unsigned int __cdecl CCS_IsConfigStringIndexConstant(int index)
{
    return reservedConfigStrings[index / 32] & (1 << (index % 32));
}

