WD_STR(0); // szInternalName
WD_STR(4); // szDisplayName
WD_STR(8); // szOverlayName
WD_MODEL_ARR(12, 16); // gunXModel
WD_MODEL(76); // handXModel
WD_STR_ARR(80, 33); // szXAnims
WD_STR(212); // szModeName
// scriptstrings hideTags[8] deja lus (u16)
// scriptstrings notetrackSoundMapKeys[16] deja lus (u16)
// scriptstrings notetrackSoundMapValues[16] deja lus (u16)
WD_FX(332); // viewFlashEffect
WD_FX(336); // worldFlashEffect
WD_SND(340); // pickupSound
WD_SND(344); // pickupSoundPlayer
WD_SND(348); // ammoPickupSound
WD_SND(352); // ammoPickupSoundPlayer
WD_SND(356); // projectileSound
WD_SND(360); // pullbackSound
WD_SND(364); // pullbackSoundPlayer
WD_SND(368); // fireSound
WD_SND(372); // fireSoundPlayer
WD_SND(376); // fireLoopSound
WD_SND(380); // fireLoopSoundPlayer
WD_SND(384); // fireStopSound
WD_SND(388); // fireStopSoundPlayer
WD_SND(392); // fireLastSound
WD_SND(396); // fireLastSoundPlayer
WD_SND(400); // emptyFireSound
WD_SND(404); // emptyFireSoundPlayer
WD_SND(408); // meleeSwipeSound
WD_SND(412); // meleeSwipeSoundPlayer
WD_SND(416); // meleeHitSound
WD_SND(420); // meleeMissSound
WD_SND(424); // rechamberSound
WD_SND(428); // rechamberSoundPlayer
WD_SND(432); // reloadSound
WD_SND(436); // reloadSoundPlayer
WD_SND(440); // reloadEmptySound
WD_SND(444); // reloadEmptySoundPlayer
WD_SND(448); // reloadStartSound
WD_SND(452); // reloadStartSoundPlayer
WD_SND(456); // reloadEndSound
WD_SND(460); // reloadEndSoundPlayer
WD_SND(464); // detonateSound
WD_SND(468); // detonateSoundPlayer
WD_SND(472); // nightVisionWearSound
WD_SND(476); // nightVisionWearSoundPlayer
WD_SND(480); // nightVisionRemoveSound
WD_SND(484); // nightVisionRemoveSoundPlayer
WD_SND(488); // altSwitchSound
WD_SND(492); // altSwitchSoundPlayer
WD_SND(496); // raiseSound
WD_SND(500); // raiseSoundPlayer
WD_SND(504); // firstRaiseSound
WD_SND(508); // firstRaiseSoundPlayer
WD_SND(512); // putawaySound
WD_SND(516); // putawaySoundPlayer
WD_SND_PTR_ARR(520, 29); // bounceSound
WD_FX(524); // viewShellEjectEffect
WD_FX(528); // worldShellEjectEffect
WD_FX(532); // viewLastShotEjectEffect
WD_FX(536); // worldLastShotEjectEffect
WD_MAT(540); // reticleCenter
WD_MAT(544); // reticleSide
WD_MODEL_ARR(700, 16); // worldModel
WD_MODEL(764); // worldClipModel
WD_MODEL(768); // rocketModel
WD_MODEL(772); // knifeModel
WD_MODEL(776); // worldKnifeModel
WD_MAT(780); // hudIcon
WD_MAT(788); // ammoCounterIcon
WD_STR(804); // szAmmoName
WD_STR(812); // szClipName
WD_STR(832); // szSharedAmmoCapName
WD_MAT(1072); // overlayMaterial
WD_MAT(1076); // overlayMaterialLowRes
WD_MAT(1304); // killIcon
WD_MAT(1316); // dpadIcon
WD_STR(1340); // szAltWeaponName
WD_MODEL(1412); // projectileModel
WD_FX(1420); // projExplosionEffect
WD_FX(1428); // projDudEffect
WD_SND(1432); // projExplosionSound
WD_SND(1436); // projDudSound
WD_FX(1704); // projTrailEffect
WD_FX(1732); // projIgnitionEffect
WD_SND(1736); // projIgnitionSound
WD_STR(1900); // accuracyGraphName[0]
WD_KNOTS(1908, 1924); // accuracyGraphKnots[0]
WD_KNOTS(1916, 1924); // originalAccuracyGraphKnots[0]
WD_STR(1904); // accuracyGraphName[1]
WD_KNOTS(1912, 1928); // accuracyGraphKnots[1]
WD_KNOTS(1920, 1928); // originalAccuracyGraphKnots[1]
WD_STR(2012); // szUseHintString
WD_STR(2016); // dropHintString
WD_STR(2036); // szScript
WD_STR(2152); // fireRumble
WD_STR(2156); // meleeImpactRumble
