#pragma once

struct OutdoorGlob // sizeof=0x40
{                                       // ...
    float bbox[2][3];                   // ...
    float scale[3];                     // ...
    float invScale[3];                  // ...
    float add[3];                       // ...
    unsigned __int8 *pic;               // ...
};
static const int outdoorMapSize[3] =
{
    0x200, 0x200, 0x100
};

int Outdoor_UpdateTransforms();
void __cdecl R_RegisterOutdoorImage(struct GfxWorld *world, const float *outdoorMin, const float *outdoorMax);
void __cdecl Outdoor_SetRendererOutdoorLookupMatrix(struct GfxWorld *world);